"""new fields in user model

Revision ID: 19103a73189e
Revises: 39bca635bf6a
Create Date: 2020-07-01 03:19:32.174495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19103a73189e'
down_revision = '39bca635bf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
